---

- hosts: all
  become: true
  tasks:

  # For Debian based distribution
  - name: Install apache and php packages for Ubuntu
    ansible.builtin.apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  # For Redhat based distribution
  - name: Install apache2 package for CentOS
    ansible.builtin.dnf:
      name:
        - httpd
        - php
      state: present
      update_cache: yes
    when: ansible_distribution in ["RHEL", "CentOS"]
