---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates (CentOS)
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]


- hosts: web_servers
  become: true
  tasks:

  - name: Install apache2 package for Ubuntu
    tags: apache,apache2,ubuntu
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package (Ubuntu)
    tags: mariadb,ubuntu,db
    ansible.builtin.apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest
