---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: all
  become: true
  tasks:

  - name: Create user Simone
    tags: always
    ansible.builtin.user:
      name: simone
      group: root
      shell: /bin/bash

  - name: add ssh key for simone
    tags: always
    ansible.posix.authorized_key:
      user: simone
      key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

  - name: add sudoers file for simone
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

- hosts: workstations
  become: true
  tasks:

  - name: Install unzip
    package:
      name: unzip

  - name: Install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: Install apache2 package for Ubuntu
    tags: apache,apache2,ubuntu
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: copy default html file for site
    tags: apache,apache2,ubuntu
    copy:
      src: ./files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package (Ubuntu)
    tags: mariadb,ubuntu,db
    ansible.builtin.apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest
