- name: Install apache2 and php package for Ubuntu
  tags: apache,apache2,ubuntu
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Copy default html file for site
  tags: apache,apache2,ubuntu
  copy:
    src: ../files/default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
