- name: Install apache and php packages
  tags: apache,apache2,ubuntu
  ansible.builtin.apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: Start and Enable apache service
  tags: apache,apache2,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Copy default html file for site
  tags: apache,apache2,ubuntu
  copy:
    src: ../files/default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
